version: '2.2'

services:
  apigateway:
    container_name: phoenix-apigateway
    image: apigateway
    build:
      context: ./apigateway
      dockerfile: ./Dockerfile
    env_file:
      - ./apigateway/apigateway.env
    ports:
      - 3000:3000
    networks:
      - default
    restart: always
  userservice:
    container_name: phoenix-userservice
    image: userservice
    build:
      context: ./userService
      dockerfile: ./Dockerfile
    env_file:
      - ./userService/userService.env
    ports:
      - 3001:3001
    networks:
      - default
    restart: always
networks:
  default:
    driver: bridge

