version: '3.4'

services:
  apigateway:
    container_name: phoenix-apigateway
    image: apigateway
    build:
      context: ./apigateway
      dockerfile: ./Dockerfile
    env_file:
      - ./apigateway/apigateway.env
    ports:
      - 3000:3000
    networks:
      - default
    restart: always
  userservice:
    container_name: phoenix-userservice
    image: userservice
    build:
      context: ./userService
      dockerfile: ./Dockerfile
    env_file:
      - ./userService/userService.env
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - default
    restart: always
  otpservice:
    container_name: phoenix-otpservice
    image: otpservice
    build:
      context: ./otpService
      dockerfile: ./Dockerfile
    env_file:
      - ./otpService/otpService.env
    ports:
      - 3002:3002
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - default
    restart: always
networks:
  default:
    driver: bridge

