http:
  port: ${HTTP_APIGATEWAY_PORT:-3000}
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  userService:
    host: ${HTTP_APIGATEWAY_HOST:-localhost}
    paths: '/api/userService/*'
  otpService:
    host: ${HTTP_APIGATEWAY_HOST:-localhost}
    paths: '/api/otpService/*'
serviceEndpoints:
  userService:
    url: 'http://${HTTP_USERSERVICE_HOST:-localhost}:${HTTP_USERSERVICE_PORT:-3001}'
  otpService:
    url: 'http://${HTTP_OTPSERVICE_HOST:-localhost}:${HTTP_OTPSERVICE_PORT:-3002}'
policies:
  - log
  - proxy
  - rate-limit
  - request-transformer
  - cors
pipelines:
  usersPipeline:
    apiEndpoints:
      - userService
    policies:
      - cors:
        - action:
            origin: ${HTTP_UI_HOST:-http://localhost:4200}
            methods: 'GET,PUT,PATCH,POST,DELETE'
      - request-transformer:
        - action:
            headers:
              add:
                x-gateway-routed: "true"
      - rate-limit:
        - action:
            max: 100
            windowMs: 1000
            rateLimitBy: "${req.ip}"
      - log:
        - action:
            message: "${req.method} ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
  otpPipeline:
    apiEndpoints:
      - otpService
    policies:
      - cors:
        - action:
            origin: ${HTTP_UI_HOST:-http://localhost:4200}
            methods: 'GET'
      - request-transformer:
        - action:
            headers:
              add:
                x-gateway-routed: "true"
      - rate-limit:
        - action:
            max: 3
            windowMs: 60000
            rateLimitBy: "${req.ip}"
      - log:
        - action:
            message: "${req.method} ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: otpService 
              changeOrigin: true
