http:
  port: ${HTTP_APIGATEWAY_PORT:-3000}
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  userService:
    host: ${HTTP_APIGATEWAY_HOST:-localhost}
    paths: '/api/userService/*'
serviceEndpoints:
  userService:
    url: 'http://${HTTP_USERSERVICE_HOST:-localhost}:${HTTP_USERSERVICE_PORT:-3001}'
policies:
  - log
  - proxy
pipelines:
  usersPipeline:
    apiEndpoints:
      - userService
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
        - action:
            message: "${req.method} ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
